### ISSUE TITLE
Datapage group by

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#102]
De datapage heeft nu één hele grote tabel. Ik wil dat deze gesplitst wordt op bepaalde (vast gekozen) waarden.
De volgende tabel:
```
| Name  | level | course    |
|-------|-------|-----------|
| Jan   | VWO   | Webdesign |
| Piet  | VWO   | course 2  |
| Klaas | HAVO  | Webdesign |
| Test  | HAVO  | course 2  |
```
Gesplitst op course geeft:

```
| Name  | level | course    |
|-------|-------|-----------|
| Jan   | VWO   | Webdesign |
| Klaas | HAVO  | Webdesign |

| Name  | level | course    |
|-------|-------|-----------|
| Piet  | VWO   | course 2  |
| Test  | HAVO  | course 2  |
```

Op welke waarde er gesplitst gaat worden moet in de code per tabel (dus per evaluation, user_data of enrollments) aangegeven kunnen worden, maar het kan ook zijn dat er nergens op gesplitst moet worden.

Verder wil ik ook dat je kunt sorteren op alle velden. In het geval van een gesplitste tabel moet je zelf even kijken hoe je dit het best kunt doen.

**2 uur**

**Comment by Jorritboer** [comment]
Waar komt de waarde vandaan waarop gesplitst moet worden? Dus niet van een knop ofzo maar uit de server?

**Comment by StevenBrons** [comment]
Die waarde mag je ergens als constante in de code inbouwen
