### ISSUE TITLE
@Beheer

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#132]
Deelnemers kunnen verwijderen
Deelnemers kunnen toevoegen
Deelnemers kunnen toevoegen vanuit inschrijvingen

**Comment by Borroot** [comment]
I would recommend using the following format for your issues:
- [ ] Deelnemers kunnen verwijderen.
- [ ] Deelnemers kunnen toevoegen.
- [ ] Deelnemers kunnen toevoegen vanuit inschrijvingen.
