### ISSUE TITLE
Authentication error login screen

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#164]
Als je niet ingelogd bent geeft het login-scherm een authentication error. Deze error moet weg gehaald worden zonder dat dit andere errors beïnvloed (dus als je een tweede (authentication) error krijgt moet deze wel zichtbaar zijn.

**0.25 uur**

**Comment by Jorritboer** [comment]
Ik ben niet in staat de bug te her-creëren. Deze zul je zelf moeten doen.
