### ISSUE TITLE
Fix spelling "assesment" -> "assessment"

### ISSUE THREAD

**Issue by apeklets** [StevenBrons/QHighschool#243]
In de hele code staat dit verkeerd gespeld. Was net een goed kwartier op zoek naar een bug toen ik er achter kwam dat ik "assessment" had staan, wat correct is, maar dat de variabele dus overal "assesment" heet. 

Deze rename moet even in 1 keer gebeuren om zoveel mogelijk merge conflicts te vermijden.
*en* het is in de SQL database tabel ook verkeerd gespeld.

**Comment by pyagnik1** [comment]
Hi 👋 @apeklets  can I fix this issue? I need to contribute to an open source project for my class. Thanks

**Comment by apeklets** [comment]
Hi @pyagnik1, sorry we did not read this message before fixing the issue. This project is not really suited for open source contribtutions (yet). Good luck with your class.
