### ISSUE TITLE
Format phone number

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#36]
Het telefoonnummer van leerlingen wordt nu gewoon als een rij getallen weergegeven. Formateer dit op een goede manier (dus ipv 003106123412 -->+31 06 123412 en 061234534 --> 06 01234534
Doe dit a.u.b. op een slimme manier en ga niet zelf proberen dit op te lossen

**0.30 uur**

**Comment by Jorritboer** [comment]
Het is mij niet gelukt, maar misschien heeft iemand hier iets aan:
https://murani.nl/blog/2015-09-28/nederlandse-reguliere-expressies/

**Comment by movieminer** [comment]
Ik zal deze issue overnemen.
