### ISSUE TITLE
Excel export

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#77]
Vind een manier om een html tabel naar Excel (xls formaat) te exporteren. Dit moet op alle browsers werken.
Dit moet vervolgens op de "Gegevens" pagina toegepast worden, ofwel, een download knop voor de gegevens pagina die alle gegevens in een excel-file zet en download.

Als #102 af is moet dit ook ge-support worden!
(Als #102 nog niet af wordt dat een onderdeel van #102)

**4 uur**

**Comment by Jorritboer** [comment]
Ik zou deze graag op me willen nemen nadat ik de gegevens pagina klaar heb.

**Comment by StevenBrons** [comment]
Super!
Ook #102 is aan de gegevens pagina gerelateerd, en zou ook goed passen

**Comment by Jorritboer** [comment]
Moet er 1 download knop zijn voor alle tabellen die op dat moment zichtbaar zijn. Of 1 knop per tabel. Of 1 knop voor alle data, dus zowel users, enrollments als evaluations?

**Comment by StevenBrons** [comment]
Eén knop voor alle op dat moment zichtbare tabellen
