### ISSUE TITLE
Design "Gegevens" page

### ISSUE THREAD

**Issue by StevenBrons** [StevenBrons/QHighschool#79]
De gegevens pagina moet ontworpen worden.

1. Een dropdown met de volgende opties: beoordeling,gebruikers,inschrijvingen, daarnaast een knop met "haal gegevens op".

2. Als er op de knop gedrukt wordt, moet de bijbehorende informatie uit fetchData gehaald worden. (zie 5)

3. Alle informatie moet in een grote (html) tabel komen te staan.

4. Users met de rollen "admin"  of "grade_admin" moeten de pagina kunnen zien

Oké, ik heb in de branch ``DataPage`` een class DataPage.js toegevoegd (op dit moment unlisted, voeg die dus ff toe aan het menu, zie 4).

5. Maak gebruik met de dummy functie fetchData, deze moet nog gemaakt worden, maar dit is wat test-data. Notice een paar dingen: de fetchData is async, ofwel, geeft niet direct een result, dus de this.state.data kan ook leeg zijn (vandaar <Progress/>). Verder is telkens de eerste index van de 2d array de koppen, ofwel, wat staat er op deze index in de rest van de array (spreekt redelijk voor zich). Verder is het **aantal** en de inhoud van de kolommen totaal anders. Het kan dus zijn dat er in het echt 12 klommen zijn (let op, dit geeft dus een scrollbar, die wel moet werken, zowel horizontaal als verticaal). 
Ofwel, het enige wat je krijgt is een 2d array met "data". Je mag er van uitgaan dat elke rij is even groot.

6. Tot slot moet je ook controlleren of er ingelogd is in de "extra beveiligde modus". Doe hier gewoon exact hetzelfde als bij de evaluation tab bij de groepen als je op bewerken klikt.

>Ik wil ook dat de header altijd zichtbaar is, dus, dat je, als je 1000 rows naar onder bent gescrolled, nogsteeds kunt zien wat elk veld is.

>> gebruik dit: https://material-ui.com/demos/tables/

**Belangrijk** Zorg ervoor dat de gegevens in een orginele html-tabel staan (voor export redenen). De styling mag uiteraard aangepast worden. Zorg voor een <table><tbody>\<tr\>\<td\> structuur, zie het internet.

**4 uur**

**Comment by movieminer** [comment]
Ik heb geen duidelijk beeld bij de Gegevens pagina. Waar komt deze pagina? En deze bevat de gegevens van studenten/leraren?

**Comment by StevenBrons** [comment]
De gegevens pagina heeft als doel als data export te dienen.
Zogenaamde school-administratoren (met role grad_admin) van de verschillende scholen van de scholengemeenschap krijgen toegang tot de site en deze pagina. Op de pagina kunnen ze vervolgens een lijst oproepen met alle gegevens die ze nodig hebben om cijfers van de QHighschool naar de eigen school-systemen over te zetten. 

Er is dus een cijfer voor een bepaalde module, de cijfer-administrator gaat naar de gegevens pagina, en vraagt "beoordelingen" op. Dit geeft vervolgens een hele grote tabel met daar alle cijfers van leerlingen per module.
